-- Run this in the Supabase SQL Editor

CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT,
  email TEXT UNIQUE,
  password TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE daily_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id),
  date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  period_start_date DATE,
  period_end_date DATE,
  cycle_day INTEGER,
  phase TEXT,
  mood_rating INTEGER,
  energy_level INTEGER
);
